name: Notify Discord on New Notices

on:
  schedule:
    - cron: "*/10 * * * *"   # 10분마다
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUTF8: "1"
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
      # 처음 한 번은 INIT_MODE=1로 실행하면 디스코드로 안 보내고 상태만 기록만 함.
      # 확인 끝나면 이 줄을 주석/삭제해도 되고 값 0으로 바꿔도 됨.
      # INIT_MODE: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python monitor.py
